### ISSUE TITLE
How can I transform tcpdump data on KDDCup99 format?

### ISSUE THREAD

**Issue by wahoyi** [igstbagusdharmaputra/NSL-KDD#1]

**Comment by igstbagusdharmaputra** [comment]
You have other solution?

Pada tanggal Kam, 11 Jun 2020 17.01, wahoyi <notifications@github.com>
menulis:

**Comment by wahoyi** [comment]
No, I used your code, but made some changes so that it runs in the latest ZeeK.

**Comment by igstbagusdharmaputra** [comment]
Thanks

Pada tanggal Kam, 11 Jun 2020 19.54, wahoyi <notifications@github.com>
menulis:
